#!/usr/bin/env python3

import sys, os, subprocess

class bcolors:
    OKGREEN = '\033[92m'
    WARNING = '\033[93m'
    FAIL = '\033[91m'
    ENDC = '\033[0m'

argc = len(sys.argv)

usage = '''USAGE:
%s 'remote' 'local_branch' 'commit_arg_1' 'commit_arg_2' ...

\tremote: the remote on which you want to push data.
\tlocal_branch: your branch you want to push news onto.
\tcommit_arg_X: corresponds to a '-m' flag of 'git commit'.'''

#Check for help flag.
if argc == 2 and (sys.argv[1] == '-h' or sys.argv[1] == '--help'):
    print(usage % (sys.argv[0] if (sys.argv and sys.argv[0]) else './push_that'))
    sys.exit(0)

#Check for a correct amount of arguments.
if argc < 3:
    print(usage % (sys.argv[0] if (sys.argv and sys.argv[0]) else './push_that'))
    print('\n%sError tracked%s: %sLack of argument(s), minimum: 3.%s'
            % (bcolors.WARNING, bcolors.ENDC, bcolors.FAIL, bcolors.ENDC))
    sys.exit(1)

commit_args = []

#Puts all of the commit arguments into 'commit_args' with the git commit flag '-m'.
for arg in sys.argv[3:]:
    commit_args.append('-m')
    commit_args.append(arg)

output = 0

#Add files Step
with open(os.devnull, 'wb') as devnull:
    try:
        output = subprocess.check_call(['git', 'add', '--all'], stdout=devnull, stderr=subprocess.STDOUT)
    except subprocess.CalledProcessError as e:
        print("%s[2/3] - %sAn unexpected error occured when adding modified files through 'git commit %s'.%s"
            % (bcolors.ENDC, bcolors.FAIL, commit_args, bcolors.ENDC))
        sys.exit(1)
if (output == 0):
    print("%s[1/3] - %sAdded all of the non-ignored files to git.%s"
            % (bcolors.ENDC, bcolors.OKGREEN, bcolors.ENDC))
else:
    print("%s[1/3] - %sAn unexpected error occured when adding modified files through 'git add --all'.%s"
            % (bcolors.ENDC, bcolors.FAIL, bcolors.ENDC))
    sys.exit(1)

#Commit Step
with open(os.devnull, 'wb') as devnull:
    try:
        output = subprocess.check_call(['git', 'commit'] + commit_args, stdout=devnull, stderr=subprocess.STDOUT)
    except subprocess.CalledProcessError as e:
        print("%s[2/3] - %sAn unexpected error occured when adding modified files through 'git commit %s'.%s"
            % (bcolors.ENDC, bcolors.FAIL, commit_args, bcolors.ENDC))
        sys.exit(1)

if (output == 0):
    print('%s[2/3] - %sSuccessfully Committed.%s'
            % (bcolors.ENDC, bcolors.OKGREEN, bcolors.ENDC))
else:
    print("%s[2/3] - %sAn unexpected error occured when adding modified files through 'git commit %s'.%s"
            % (bcolors.ENDC, bcolors.FAIL, commit_args, bcolors.ENDC))
    sys.exit(1)

#Push Step
with open(os.devnull, 'wb') as devnull:
    try:
        output = subprocess.check_call(['git', 'push', sys.argv[1], sys.argv[2]], stdout=devnull, stderr=subprocess.STDOUT)
    except subprocess.CalledProcessError as e:
        print("%s[3/3] - %sAn unexpected error occured when adding modified files through 'git push %s'.%s"
                % (bcolors.ENDC, bcolors.FAIL, sys.argv[1] + ' ' + sys.argv[2], bcolors.ENDC))
        sys.exit(1)

if (output == 0):
    print("%s[3/3] - %sPushed data to %s from %s.%s" % (bcolors.ENDC, bcolors.OKGREEN, sys.argv[1], sys.argv[2], bcolors.ENDC))
else:
    print("%s[3/3] - %sAn unexpected error occured when adding modified files through 'git push %s'.%s"
                % (bcolors.ENDC, bcolors.FAIL, sys.argv[1] + ' ' + sys.argv[2], bcolors.ENDC))
    sys.exit(1)

sys.exit(0)
